import type { Metadata } from 'next';
import { quickSandFont } from '@/components/config';
import { AppProvider } from '@/components/provider';
import './custom.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <html lang="en" className={quickSandFont.className} suppressHydrationWarning>
        <body className="min-h-screen flex justify-center items-center">{children}</body>
      </html>
    </AppProvider>
  );
}
